#pragma once

#define ASCII_BORDER_TOP    2
#define ASCII_BORDER_RIGHT  3
#define ASCII_BORDER_BOTTOM 4
#define ASCII_BORDER_LEFT   5

#define ASCII_BORDER_TOP_RIGHT    6
#define ASCII_BORDER_BOTTOM_RIGHT 7
#define ASCII_BORDER_BOTTOM_LEFT  8
#define ASCII_BORDER_TOP_LEFT     9

#define ASCII_BORDER_ROUND_TOP_RIGHT    10
#define ASCII_BORDER_ROUND_BOTTOM_RIGHT 11
#define ASCII_BORDER_ROUND_BOTTOM_LEFT  12
#define ASCII_BORDER_ROUND_TOP_LEFT     13

#define ASCII_SQUARE_EMPTY 14
#define ASCII_SQUARE_FULL  15

#define ASCII_TRANGLE_TOP    16
#define ASCII_TRANGLE_RIGHT  17
#define ASCII_TRANGLE_BOTTOM 18
#define ASCII_TRANGLE_LEFT   19

#define ASCII_SQUARE_INSET 30
#define ASCII_CURSOR       31
